#!/bin/sh

# S P A C E B A R 

# NOTE: 
  # Colors are in 8bit Hex segments using the ARGB format. 
  # Example `prefix 0x Alpha 90 Red ac Blue ca Green 5f`
# TODO: Create Function to hide spacebar (kill it) and update yabai padding
# TODO: Write Script that shows BTC and VTI up or down percentage for the day. 
# TODO: Create Script that will show current playing track information in center. Toggle with SKHD.
# TODO: Create a script to Cycle through shell commands
# TODO: Try This Format When Sperators are released " %R |   %m/%d/%y"


# Pywal
  # Load Colors
    . $HOME/.cache/wal/colors.sh

# Positioning
  spacebar -m config position                    top
  spacebar -m config display                     main
  spacebar -m config height                      26
  spacebar -m config padding_left                20
  spacebar -m config padding_right               20
  spacebar -m config spacing_left                25
  spacebar -m config spacing_right               15

# Fonts
  spacebar -m config text_font                   'Iosevka Nerd Font:Mono:14.0'
  spacebar -m config icon_font                   'Iosevka Nerd Font:Mono:14.0'

# Icons
  spacebar -m config power_icon_strip            '| ' '|  '
  spacebar -m config space_icon                  ''
  spacebar -m config space_icon_strip            'ﮟ' '' '' '' '' 
  spacebar -m config clock_icon                  '|  '
  spacebar -m config dnd_icon                    '| '
  spacebar -m config right_shell_icon            '| '

# Colors
  spacebar -m config background_color            0xF0${background:1}
  spacebar -m config foreground_color            0xff${color1:1}
  spacebar -m config power_icon_color            0xff${color3:1}
  spacebar -m config battery_icon_color          0xff${color3:1}
  spacebar -m config dnd_icon_color              0xff${color3:1}
  spacebar -m config clock_icon_color            0xff${color3:1}
  spacebar -m config right_shell_icon_color      0xff${color3:1}
  spacebar -m config space_icon_color            0xff${color3:1}
  spacebar -m config space_icon_color_secondary  0xff${color4:1}
  spacebar -m config space_icon_color_tertiary   0xff${color5:1}

# Features
  spacebar -m config title                       on
  spacebar -m config spaces                      on
  spacebar -m config clock                       on
  spacebar -m config power                       on
  spacebar -m config spaces_for_all_displays     on
  spacebar -m config right_shell                 on

# Configuration
  spacebar -m config clock_format                ' %B %d, %Y %R'
  spacebar -m config right_shell_command       "$HOME/.config/bin/helpers -i;"

echo "spacebar configuration loaded.."
