# Z S H R C

# I N I T
source $HOME/.config/zsh/env.zsh
source $HOME/.config/zsh/paths.zsh
source $HOME/.config/zsh/zinit_conf.zsh
source $HOME/.config/zsh/functions.zsh
source $HOME/.config/zsh/aliases.zsh
source $HOME/.config/zsh/pfetch.zsh
source $HOME/.config/zsh/exa.zsh
# NOTE: Depending on setup ASDF location might differ 
source /opt/homebrew/opt/asdf/libexec/asdf.sh

# Add Case Insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# H I S T O R Y
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY

# R U N  B E F O R E  P R O M P T 
pfetch
cs_spectrum

# P R O M P T - S T A R S H I P
eval "$(starship init zsh)"
