# Z S H R C

# I N I T
source $HOME/.config/zsh/exports.zsh
source $HOME/.config/zsh/paths.zsh
source $HOME/.config/zsh/plugins.zsh
source $HOME/.config/zsh/functions.zsh
source $HOME/.config/zsh/aliases.zsh
# Once feature complete add it to github and isntall it with zinit
source $HOME/.config/zsh/tatl.zsh
# NOTE: Depending on setup ASDF location might differ 
source /opt/homebrew/opt/asdf/libexec/asdf.sh
# Source Rust 
source $HOME/.cargo/env

# Add Case Insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

# H I S T O R Y
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt INC_APPEND_HISTORY

# R U N  B E F O R E  P R O M P T 
pfetch
cs_spectrum

# P R O M P T - S T A R S H I P
eval "$(starship init zsh)"


# BEGIN_KITTY_SHELL_INTEGRATION
if test -e "/Applications/kitty.app/Contents/Resources/kitty/shell-integration/kitty.zsh"; then source "/Applications/kitty.app/Contents/Resources/kitty/shell-integration/kitty.zsh"; fi
# END_KITTY_SHELL_INTEGRATION
